name: Build Debug Version

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-android-debug:
    name: Build Android Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate native Android files
        run: npx expo prebuild -p android

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Create build directory
        run: mkdir -p ./build

      - name: Copy APK to build directory
        run: cp android/app/build/outputs/apk/debug/app-debug.apk ./build/NeverMiss-debug.apk

      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-debug-app
          path: ./build/NeverMiss-debug.apk
          retention-days: 7

  build-ios-debug:
    name: Build iOS Debug App
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate native iOS files
        run: npx expo prebuild -p ios

      - name: Install Pods
        run: |
          cd ios
          pod install

      - name: Build iOS App for Simulator
        run: |
          cd ios
          xcodebuild -workspace NeverMiss.xcworkspace -scheme NeverMiss -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' build
      
      - name: Create build directory
        run: mkdir -p ./build/ios-simulator
      
      - name: Copy app to build directory
        run: |
          cd ios/build/Build/Products/Debug-iphonesimulator
          cp -r NeverMiss.app ../../../../../build/ios-simulator/
      
      - name: Compress iOS simulator app
        run: |
          cd build
          zip -r NeverMiss-debug-simulator.zip ios-simulator

      - name: Upload iOS simulator app artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-debug-simulator
          path: ./build/NeverMiss-debug-simulator.zip
          retention-days: 7

  create-debug-release:
    name: Create Debug Release
    needs: [build-android-debug]
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Create build directory
        run: mkdir -p ./build
        
      - name: Download Android Debug artifact
        uses: actions/download-artifact@v3
        with:
          name: android-debug-app
          path: ./build
          
      - name: Download iOS simulator artifact
        uses: actions/download-artifact@v3
        with:
          name: ios-debug-simulator
          path: ./build
        continue-on-error: true

      - name: Generate release notes
        id: release_notes
        run: |
          echo "## NeverMiss Debug Build ($(date +'%Y-%m-%d'))" > ./build/RELEASE_NOTES.md
          echo "" >> ./build/RELEASE_NOTES.md
          echo "### 调试版本说明" >> ./build/RELEASE_NOTES.md
          echo "" >> ./build/RELEASE_NOTES.md
          echo "此版本为开发调试版本，未使用签名密钥构建，仅用于测试。" >> ./build/RELEASE_NOTES.md
          echo "" >> ./build/RELEASE_NOTES.md
          echo "- 分支: ${{ github.ref_name }}" >> ./build/RELEASE_NOTES.md
          echo "- 提交: ${{ github.sha }}" >> ./build/RELEASE_NOTES.md
          echo "- 构建时间: $(date +'%Y-%m-%d %H:%M:%S')" >> ./build/RELEASE_NOTES.md

      - name: Create Debug Release
        uses: softprops/action-gh-release@v1
        with:
          name: Debug Build $(date +'%Y-%m-%d')
          tag_name: debug-${{ github.sha }}
          draft: false
          prerelease: true
          body_path: ./build/RELEASE_NOTES.md
          files: |
            ./build/NeverMiss-debug.apk
            ./build/NeverMiss-debug-simulator.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 