name: Build Debug Version

on:
  push:
    branches: [ main, master, develop, feature/*, release/* ]
    tags:
      - 'v*.*.*'  # 添加版本标签触发条件，如v1.1.0
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:  # 允许手动触发

# 添加权限配置
permissions:
  contents: write  # 允许工作流写入仓库内容(必须有这个权限才能创建Releases)
  pull-requests: write  # 可选，如果需要评论PR
  issues: write  # 可选，如果需要操作Issues

jobs:
  build-android-debug:
    name: Build Android Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get version from package.json
        id: package_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "检测到package.json版本号: $VERSION"
          
          # 检查version.ts文件是否已经更新
          echo "验证config/version.ts中的版本号是否与package.json同步..."
          TS_VERSION=$(node -e "try { const v = require('./config/version').APP_INFO.VERSION; console.log(v); } catch(e) { console.log('error'); }")
          echo "config/version.ts中版本号: $TS_VERSION"
          
          if [ "$TS_VERSION" != "$VERSION" ] && [ "$TS_VERSION" != "error" ]; then
            echo "警告: config/version.ts中的版本号($TS_VERSION)与package.json中的版本号($VERSION)不一致"
            echo "版本文件不同步，但继续构建过程..."
          fi

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 添加缓存加速依赖安装
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline

      - name: Generate native Android files
        run: npx expo prebuild -p android --clean

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # 添加Gradle缓存
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug -PreactNativeDevSupport=false -PreactNativeJsEngine=hermes --no-daemon --max-workers=2

      - name: Create build directory
        run: mkdir -p ./build

      - name: Copy APK to build directory
        run: cp android/app/build/outputs/apk/debug/app-debug.apk ./build/NeverMiss-debug.apk

      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-app
          path: ./build/NeverMiss-debug.apk
          retention-days: 7

  build-ios-debug:
    name: Build iOS Debug App
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 添加缓存加速依赖安装
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline

      - name: Generate native iOS files
        run: npx expo prebuild -p ios --clean

      # 添加CocoaPods缓存
      - name: Cache Pods
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: |
          cd ios
          pod install

      - name: Build iOS App for Simulator
        run: |
          cd ios
          xcodebuild -workspace NeverMiss.xcworkspace -scheme NeverMiss -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" CODE_SIGN_ENTITLEMENTS="" RCT_NO_LAUNCH_PACKAGER=1 NO_FLIPPER=1 COMPILER_INDEX_STORE_ENABLE=NO -quiet build

      - name: Find and prepare iOS app
        run: |
          DERIVED_APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "NeverMiss.app" -type d | grep -v "SourcePackages" | head -n 1)
          if [ ! -z "$DERIVED_APP_PATH" ]; then
            mkdir -p ./build/ios-simulator
            cp -r "$DERIVED_APP_PATH" ./build/ios-simulator/
            cd build
            zip -r -y NeverMiss-debug-simulator.zip ios-simulator
          else
            echo "警告: 找不到iOS构建产物"
            mkdir -p ./build
            echo "Placeholder" > ./build/NeverMiss-debug-simulator.zip
          fi

      - name: Upload iOS simulator app artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-debug-simulator
          path: ./build/NeverMiss-debug-simulator.zip
          retention-days: 7

  create-debug-release:
    name: Create Debug Release
    needs: [build-android-debug]
    runs-on: ubuntu-latest
    # 在推送到main或develop分支、使用标签或手动触发时创建发布
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Get version from package.json
        id: package_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "检测到package.json版本号: $VERSION"

      - name: Download artifacts
        run: |
          mkdir -p ./build
      
      - name: Download Android Debug artifact
        uses: actions/download-artifact@v4
        with:
          name: android-debug-app
          path: ./build
          
      - name: Download iOS simulator artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-debug-simulator
          path: ./build
        continue-on-error: true

      - name: Check iOS simulator file
        id: check_ios_file
        run: |
          if [ -f "./build/NeverMiss-debug-simulator.zip" ] && [ $(stat -c%s "./build/NeverMiss-debug-simulator.zip") -gt 1000 ]; then
            echo "ios_file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "ios_file_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Set release tag name
        id: set_tag
        run: |
          if [[ ${{ github.ref }} == refs/tags/v* ]]; then
            TAG="${{ github.ref_name }}"
          else
            TAG="v${{ steps.package_version.outputs.version }}-debug-${{ github.sha }}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Generate release notes
        run: |
          if [[ ${{ github.ref }} == refs/tags/v* ]]; then
            TITLE="NeverMiss 版本 ${{ steps.set_tag.outputs.tag }} ($(date +'%Y-%m-%d'))"
            DESC="这是 NeverMiss 应用的自动构建版本。"
          else
            TITLE="NeverMiss v${{ steps.package_version.outputs.version }} 调试构建"
            DESC="此版本为开发调试版本，基于 package.json 中的版本号 v${{ steps.package_version.outputs.version }}，未使用签名密钥构建，仅用于测试。"
          fi
          
          cat > ./build/RELEASE_NOTES.md << EOF
          ## ${TITLE}
          
          ### 版本说明
          
          ${DESC}
          
          - 分支: ${{ github.ref_name }}
          - 提交: ${{ github.sha }}
          - 构建时间: $(date +'%Y-%m-%d %H:%M:%S')
          - 版本: v${{ steps.package_version.outputs.version }}
          EOF

      - name: Create Debug Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ startsWith(github.ref, 'refs/tags/v') && format('NeverMiss {0}', steps.set_tag.outputs.tag) || format('NeverMiss v{0} 调试构建', steps.package_version.outputs.version) }}
          tag_name: ${{ steps.set_tag.outputs.tag }}
          draft: false
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          body_path: ./build/RELEASE_NOTES.md
          files: |
            ./build/NeverMiss-debug.apk
            ${{ steps.check_ios_file.outputs.ios_file_exists == 'true' && './build/NeverMiss-debug-simulator.zip' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 